set(HDF5_PATH "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/hdf5/1.12.3")
set(NETCDF_C_PATH "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/netcdf/4.9.2")
set(NETCDF_FORTRAN_PATH "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/netcdf-fortran/4.6.1")
set(PNETCDF_PATH "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/pnetcdf/1.12.3")
set(LAPACK_PATH "/opt/gridware/depots/8e896c5a/el7/pkg/libs/lapack/3.5.0/gcc-4.8.5")
set(BLAS_PATH "/opt/gridware/depots/8e896c5a/el7/pkg/libs/blas/3.6.0/gcc-4.8.5/")
set(ESMF_LIBDIR "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/esmf/8.6/lib")
set(PIO_LIBDIR "/mnt/iusers01/fatpou01/sees01/a16404ys/privatemodules_packages/csf3/apps/gcc/pio2/2.6.2/lib")

string(APPEND SLIBS " -L$ENV{HDF5_PATH}/lib -lhdf5_fortran -lhdf5 -lhdf5_hl -lhdf5hl_fortran -Wl,-rpath,${HDF5_PATH}/lib")
string(APPEND SLIBS " -L${NETCDF_C_PATH}/lib -L${NETCDF_FORTRAN_PATH}/lib -lnetcdff -lnetcdf -lm")
string(APPEND SLIBS " -L${PNETCDF_PATH}/lib -Wl,-rpath,${PNETCDF_PATH}/lib")
string(APPEND SLIBS " -L${LAPACK_PATH}/lib -Wl,-rpath,${LAPACK_PATH}/lib -llapack")
string(APPEND SLIBS " -L${BLAS_PATH} -Wl,-rpath,${BLAS_PATH} -lblas")
string(APPEND SLIBS " -ldl -L${ESMF_LIBDIR} -Wl,-rpath,${ESMF_LIBDIR}")
string(APPEND SLIBS " -ldl -L${PIO_LIBDIR} -Wl,-rpath,${PIO_LIBDIR}")